---
- name: Create openstack keypair for {{ deploy_rhelai_vm_name }}
  ansible.builtin.command: "{{ deploy_rhelai_openstack_command }} --insecure keypair create {{ deploy_rhelai_vm_name }}"
  environment:
    OS_CLOUD: default
  no_log: true
  register: output
  changed_when: true

- name: Write ssh key to file for {{ deploy_rhelai_vm_name }}
  ansible.builtin.copy:
    content: "{{ output.stdout }}\n"
    dest: "{{ deploy_rhelai_private_key_file }}"
    mode: "0600"

- name: Create VM {{ deploy_rhelai_vm_name }}
  ansible.builtin.command: |
    {{ deploy_rhelai_openstack_command }} --insecure server create --flavor {{ deploy_rhelai_flavor }} \
    --image {{ deploy_rhelai_image_name }} --key-name {{ deploy_rhelai_vm_name }} \
    --nic net-id=private {{ deploy_rhelai_vm_name }} --security-group basic --wait
  environment:
    OS_CLOUD: default
  changed_when: true

- name: Add floating IP to {{ deploy_rhelai_vm_name }}
  ansible.builtin.command: |
    {{ deploy_rhelai_openstack_command }} --insecure server add floating ip {{ deploy_rhelai_image_name }} {{ deploy_rhelai_floating_ip }}
  environment:
    OS_CLOUD: default
  changed_when: true

- name: Poll for SSH to be available on {{ deploy_rhelai_vm_name }}
  ansible.builtin.command: |
    ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
    -i {{ deploy_rhelai_private_key_file }} cloud-user@{{ deploy_rhelai_floating_ip }}
  retries: 60  # 60 * 10 = 10 mins
  delay: 10
  register: result
  until: result.rc == 0
  changed_when: false
