---
- name: Run ilab system info to verify it works
  ansible.builtin.command: ilab system info
  register: ilab_sys_info_result
  failed_when: ilab_sys_info_result.rc != 0
  changed_when: false

- name: TEST Check if dummy workload (running a workload which utilizes GPUs) is working
  ansible.builtin.command: /tmp/scripts/run_ilab_sanity_check.sh
  register: ilab_sanity_result
  failed_when: ilab_sanity_result.rc != 0
  changed_when: false

- name: Run model performance and monitoring check
  when: model_tests_enabled | bool
  block:
    - ansible.builtin.import_tasks: ilab_config.yaml  # noqa: name[missing]
    - ansible.builtin.import_tasks: model_download_and_serve.yaml  # noqa: name[missing]
    - ansible.builtin.import_tasks: model_performance.yaml  # noqa: name[missing]
    - ansible.builtin.import_tasks: nginx_ssl.yaml  # noqa: name[missing]
      when: nginx_enabled | bool
