---
- name: Setup
  become: true
  ansible.builtin.import_tasks: setup.yaml
- name: Check GPUs
  ansible.builtin.import_tasks: gpus.yaml
- name: GPUs Assertions  # noqa: ignore-errors
  ansible.builtin.import_tasks: gpus_assertions.yaml
  ignore_errors: true
- name: Check NVIDIA
  ansible.builtin.import_tasks: nvidia.yaml
- name: NVIDIA Assertions  # noqa: ignore-errors
  ansible.builtin.import_tasks: nvidia_assertions.yaml
  ignore_errors: true
- name: Check iLab
  ansible.builtin.import_tasks: ilab.yaml
- name: Cleanup
  become: true
  ansible.builtin.import_tasks: cleanup.yaml
