---
- name: RHEL AI VM setup
  when: deploy_rhelai_enabled | bool
  block:
    - name: VM Cleanup (Pre)
      ansible.builtin.import_tasks: vm_cleanup.yaml
      when: deploy_rhelai_pre_cleanup_enabled | bool

    - name: Set up SSH key for VM
      ansible.builtin.import_tasks: vm_sshkey.yaml

    - name: VM Deploy
      ansible.builtin.import_tasks: vm_deploy.yaml
